### ISSUE TITLE
Change DiagnosticableMixin to Diagnosticable

### ISSUE THREAD

**Issue by jonasbeyer** [nubank/i18next#16]
`DiagnosticableMixin` has been removed in Flutter 1.20.0. The `I18NextOptions` class should implement `Diagnosticable` instead. (https://github.com/nubank/i18next/blob/master/lib/src/options.dart)

Flutter PR:
https://github.com/flutter/flutter/pull/58635

**Comment by williamhjcho** [comment]
Thanks for the contribution @jonasbeyer!
