### ISSUE TITLE
Null-Safety

### ISSUE THREAD

**Issue by Ahmadre** [nubank/i18next#33]
Is it possible to migrate to null-safety?

Flutter and most of the packages out there are already migrated and stable but this packages makes still problems

**Comment by williamhjcho** [comment]
Hi @Ahmadre 
Sure! We'll probably have a null-safety version (not in master directly) this week.

Sorry for the delay!

**Comment by wferem1** [comment]
Hi @williamhjcho,
there is still no stable nullsafety release available, any update on when you're gonna publish this?

**Comment by williamhjcho** [comment]
So sorry for the delay!!!

Merged and released into `0.4.1` #34

**Comment by Ahmadre** [comment]
> So sorry for the delay!!!
> 
> Merged and officialized the release into `0.4.1` #34

Thank you so much william :)))
